### PR TITLE
 VS2017 Conversion and added NetStandard2.0 support 

### LINKED ISSUE #5: Suggested mods
Hi! 

I have the following suggestions for the project - if you think they're good, I can submit a pull request:
- Use JSON.NET instead of ServiceStack because it's used more widely and there's a high chance it will already be there. 
- Add a parameter which will allow you to specify which fields are displayed in table format below the message.

Thanks

### LINKED ISSUE #11: Nuget package has wrong dependencies
Hi,
I have had som issues with Nlog.Slack.
I found out that a dependency is now NewtonSoft.Json but it isn't stated in the Nlog.Slack nuget package.
Instead a dependency is ServiceStack.Text which I thought you removed according to this issue:
https://github.com/eth0izzle/NLog.Slack/pull/4

Also, when I download the source the version on Nlog.Slack is 1.0.1, not 1.0.2. Isn't the latest code in git?

Regards,
Christian

### LINKED ISSUE #13: Missing correct AsyncLogEventInfo callback
When overriding:

`protected override void Write(AsyncLogEventInfo info)`

Then you should also need to notify when the AsyncLogEventInfo completes with success.

I would probably remove the try-catch and Error-event from SlackClient, and add this **bold line**:

protected override void Write(AsyncLogEventInfo info)
{
  try
  {
    this.SendToSlack(info);
    **info.Continuation(null);**
  }
  catch (Exception e)
  {
    info.Continuation(e);
  }
}

### LINKED ISSUE #14: supporting .net standard 2
Is there any plan to support .net standard 2 any soon?

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #13 and resolves #14 and resolves  #11 and resolves #5 (Can add own contextproperty-items as fields)

Now one should create nuget-package using dotnet-tooling:

> dotnet pack NLog.Slack --configuration Release

### CODE REVIEW

**Comment by snakefoot** [comment]
@eth0izzle Problems with publishing the nuget-package?

**Comment by snakefoot** [comment]
@eth0izzle Another polite poke.

**Comment by snakefoot** [comment]
@eth0izzle Any chance for a release on nuget?

**Comment by eth0izzle** [comment]
@snakefoot sorry for the delay. I'll try and push it up this weekend.

**Comment by snakefoot** [comment]
@eth0izzle Maybe a release the coming weekend?

**Comment by snakefoot** [comment]
@eth0izzle Before making a release, then please merge #17

**Comment by snakefoot** [comment]
@eth0izzle Thank you for the nuget-package. But could you re-add netstandard2.0 as targetplatform ?

https://github.com/eth0izzle/NLog.Slack/blob/c8f03ecc560d7e0fb929c8747fae394c2efa49a0/NLog.Slack/NLog.Slack.csproj#L4

So it becomes:

`<TargetFrameworks>net45;netstandard2.0</TargetFrameworks>`

**Comment by snakefoot** [comment]
Also curious why you have removed:

`var message = Layout.Render(info.LogEvent);`

Now it is no longer configurable how the LogEvent is formatted as Slack-message.

**Comment by eth0izzle** [comment]
@snakefoot hmm not sure what happened there. I'll take a look.

**Comment by snakefoot** [comment]
Also be aware that this:

`                .WithMessage(info.LogEvent.Message);`

Is not the same as this:

```
var message = Layout.Render(info.LogEvent);
WithMessage(message);
```

Because `info.LogEvent.Message` is the message-template / unformatted-message. Ex `"Hello {0}"`

The NLog Layout allows one to generate complex output. Using the LayoutRenderers (Ex. `${level}`) or JsonLayout/CsvLayout/XmlLayout.

**Pull request merged**
