### PR TITLE
Added NetStandard2.0 support (again)

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
Remember you need to build the package like this:

> dotnet pack NLog.Slack --configuration Release

The current nuget-package dependens on NLog 3.1.0: https://www.nuget.org/packages/NLog.Slack/1.0.4 (Which is wrong)

**Comment by snakefoot** [comment]
@eth0izzle Any chance to have this merged with a new nuget-package release ?

**Comment by snakefoot** [comment]
@eth0izzle Thank you for the merge. Any chance for publishing the `dotnet pack` result ?

**Comment by eth0izzle** [comment]
@snakefoot New major version published with .netstandard2.0 support - thanks: https://www.nuget.org/packages/NLog.Slack/2.0.0

**Pull request merged**
